// --- Pins --- //
// Pins - DC Motors
#define LEFT_MOTOR_FORWARDS_PIN 25
#define LEFT_MOTOR_REVERSE_PIN 26
#define RIGHT_MOTOR_FORWARDS_PIN 33
#define RIGHT_MOTOR_REVERSE_PIN 32
#define VERTICAL_MOTOR_FORWARDS_PIN 15
#define VERTICAL_MOTOR_REVERSE_PIN 2

// Pins - Servos
#define BASE_SERVO_PIN 5
#define SHOULDER_SERVO_PIN 4
#define ELBOW_SERVO_PIN 14
#define WRIST_SERVO_PIN 12
#define CLAW_SERVO_PIN 13

// Pins - Sensors
#define LEFT_REFLECTANCE_PIN ADC1_CHANNEL_2 // 38
#define RIGHT_REFLECTANCE_PIN ADC1_CHANNEL_1 // 37
#define FORWARD_LEFT_REFLECTANCE_PIN ADC1_CHANNEL_6 // 34
#define FORWARD_RIGHT_REFLECTANCE_PIN ADC1_CHANNEL_7 // 35
#define I2C_PIN_1 21
#define I2C_Pin_2 22

// Pins - Switches
#define INITIALIZE_SWITCH_PIN 7
#define RESET_SWITCH_PIN 8

// --- Channels --- //
// Channels - Drive Motors
#define LEFT_FORWARDS_CHANNEL 0
#define LEFT_REVERSE_CHANNEL 1
#define RIGHT_FORWARDS_CHANNEL 2
#define RIGHT_REVERSE_CHANNEL 3
#define VERTICAL_FORWARDS_CHANNEL 4
#define VERTICAL_REVERSE_CHANNEL 5

// Channels - Arm Servos
#define BASE_SERVO_CHANNEL 8
#define SHOULDER_SERVO_CHANNEL 7
#define ELBOW_SERVO_CHANNEL 6
#define WRIST_SERVO_CHANNEL 9
#define CLAW_SERVO_CHANNEL 10
